# Generated by Django 5.0.4 on 2024-04-30 05:49

import board.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=board.models.Board.get_default_board, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.board'),
        ),
    ]
